name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out the code.."
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "Setting up node.."
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: echo "Installing dependencies.."
      - name: Install dependencies
        run: npm ci
      - run: echo "Releasing.."
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
